=== jQAssistant/jqassistant/core/schemata/src/main/resources/META-INF/rule/xsd/jqassistant-rule-v1.10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://schema.jqassistant.org/rule/v1.10"
           targetNamespace="http://schema.jqassistant.org/rule/v1.10"
           elementFormDefault="qualified">

    <xs:element name="jqassistant-rules">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="concept" type="tns:conceptType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="constraint" type="tns:constraintType" minOccurs="0"
                            maxOccurs="unbounded"/>
                <xs:element name="group" type="tns:groupType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="referenceableType" abstract="true">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="sourceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="language" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="parameterType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="tns:parameterTypes" use="required"/>
        <xs:attribute name="defaultValue" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="parameterTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="char"/>
            <xs:enumeration value="byte"/>
            <xs:enumeration value="short"/>
            <xs:enumeration value="int"/>
            <xs:enumeration value="long"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="String"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="propertyType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="severityEnumType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="blocker"/>
            <xs:enumeration value="critical"/>
            <xs:enumeration value="major"/>
            <xs:enumeration value="minor"/>
            <xs:enumeration value="info"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="referenceType">
        <xs:attribute name="refId" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="optionalReferenceType">
        <xs:complexContent>
            <xs:extension base="tns:referenceType">
                <xs:attribute name="optional" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="includedReferenceType">
        <xs:complexContent>
            <xs:extension base="tns:referenceType">
                <xs:attribute name="severity" type="tns:severityEnumType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="verificationType">
        <xs:choice>
            <xs:element name="rowCount" type="tns:rowCountVerificationType"/>
            <xs:element name="aggregation" type="tns:aggregationVerificationType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="rowCountVerificationType">
        <xs:attribute name="min" type="xs:int"/>
        <xs:attribute name="max" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="aggregationVerificationType">
        <xs:attribute name="column" type="xs:string"/>
        <xs:attribute name="min" type="xs:int"/>
        <xs:attribute name="max" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="severityRuleType" abstract="true">
        <xs:complexContent>
            <xs:extension base="tns:referenceableType">
                <xs:attribute name="severity" type="tns:severityEnumType"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="executableRuleType" abstract="true">
        <xs:complexContent>
            <xs:extension base="tns:severityRuleType">
                <xs:sequence>
                    <xs:element name="requiresConcept" type="tns:optionalReferenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                    <xs:element name="requiresParameter" type="tns:parameterType" minOccurs="0"
                                maxOccurs="unbounded"/>
                    <xs:element name="description" type="xs:string" minOccurs="0"/>
                    <xs:element name="deprecated" type="xs:string" minOccurs="0"/>
                    <xs:choice>
                        <xs:element name="source" type="tns:sourceType"/>
                        <xs:element name="cypher" type="xs:string"/>
                        <xs:element name="script" type="tns:sourceType"/>
                    </xs:choice>
                    <xs:element name="verify" type="tns:verificationType" minOccurs="0"/>
                    <xs:element name="report" type="tns:reportType" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="conceptType">
        <xs:complexContent>
            <xs:extension base="tns:executableRuleType">
                <xs:sequence>
                    <xs:element name="providesConcept" type="tns:referenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="constraintType">
        <xs:complexContent>
            <xs:extension base="tns:executableRuleType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="tns:severityRuleType">
                <xs:sequence>
                    <xs:element name="includeConcept" type="tns:includedReferenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                    <xs:element name="includeConstraint" type="tns:includedReferenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                    <xs:element name="includeGroup" type="tns:includedReferenceType" minOccurs="0"
                                maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="reportType">
        <xs:sequence>
            <xs:element name="property" type="tns:propertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="primaryColumn" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== jQAssistant/jqassistant/core/rule/src/test/resources/executables.xml
<jqassistant-rules xmlns="http://schema.jqassistant.org/rule/v1.10"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://schema.jqassistant.org/rule/v1.10 http://schema.jqassistant.org/rule/jqassistant-rule-v1.10.xsd">

    <concept id="test:CypherConcept">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <cypher><![CDATA[
            Cypher Concept
        ]]></cypher>
    </concept>

    <concept id="test:ScriptConcept">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <script language="javascript"><![CDATA[
            Script Concept
        ]]></script>
    </concept>

    <concept id="test:SourceConcept">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <source language="cypher"><![CDATA[
          Source Concept
        ]]></source>
    </concept>

    <concept id="test:SourceConceptUpperCase">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <source language="CYPHER"><![CDATA[
          Source Concept (upper case)
        ]]></source>
    </concept>


    <constraint id="test:CypherConstraint">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <cypher><![CDATA[
            Cypher Constraint
        ]]></cypher>
    </constraint>

    <constraint id="test:ScriptConstraint">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <script language="javascript"><![CDATA[
            Script Constraint
        ]]></script>
    </constraint>

    <constraint id="test:SourceConstraint">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <source language="cypher"><![CDATA[
            Source Constraint
        ]]></source>
    </constraint>

    <constraint id="test:SourceConstraintUpperCase">
        <requiresConcept refId="test:RequiredConcept"/>
        <description></description>
        <source language="CYPHER"><![CDATA[
            Source Constraint (upper case)
        ]]></source>
    </constraint>

</jqassistant-rules>

=== jQAssistant/jqassistant/plugin/java/src/it/jpms/jqassistant/it.xml
<jqassistant-rules xmlns="http://schema.jqassistant.org/rule/v1.10"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://schema.jqassistant.org/rule/v1.10 http://schema.jqassistant.org/rule/jqassistant-rule-v1.10.xsd">

    <group id="it">
        <includeConcept refId="it:*" severity="blocker" />
    </group>

    <concept id="it:Module1AnnotatedByDeprecated">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (module1)-[:ANNOTATED_BY]->()-[:OF_TYPE]->(:Type{fqn:"java.lang.Deprecated"})
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1RequiresJacksonCore">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (jacksonCore:Artifact{name:"jackson-core"}),
              (jacksonCore)-[:CONTAINS]->(module2:Java:Module{fqn:"com.fasterxml.jackson.core"}),
              (module1)-[:REQUIRES]->(module2)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1ExportsApiPackage">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(api:Java:Package{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api"}),
              (module1)-[:EXPORTS]->(exportedPackage:Java:ExportedPackage),
              (exportedPackage)-[:OF_PACKAGE]->(api)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1ExportsImplPackageToModule2">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(impl:Java:Package{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.impl"}),
              (module1)-[:EXPORTS]->(exportedPackage:Java:ExportedPackage),
              (exportedPackage)-[:OF_PACKAGE]->(impl),
              (exportedPackage)-[:TO_MODULE]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (artifact1)-[:REQUIRES]->(module2)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1OpensApiPackage">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(api:Java:Package{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api"}),
              (module1)-[:OPENS]->(openPackage:Java:OpenPackage),
              (openPackage)-[:OF_PACKAGE]->(api)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1OpensImplPackageToModule2">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(impl:Java:Package{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.impl"}),
              (module1)-[:OPENS]->(openPackage:Java:OpenPackage),
              (openPackage)-[:OF_PACKAGE]->(impl),
              (openPackage)-[:TO_MODULE]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (artifact1)-[:REQUIRES]->(module2)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1ProvidesService">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(serviceType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api.MyService"}),
              (artifact1)-[:CONTAINS]->(providerType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.impl.MyServiceImpl"}),
              (module1)-[:PROVIDES]->(providedService:Java:ProvidedService),
              (providedService)-[:OF_TYPE]->(serviceType),
              (providedService)-[:WITH_PROVIDER]->(providerType)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module1ProvidesInnerService">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(serviceType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api.MyService$InnerService"}),
              (artifact1)-[:CONTAINS]->(providerType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.impl.MyServiceImpl$InnerServiceImpl"}),
              (module1)-[:PROVIDES]->(providedService:Java:ProvidedService),
              (providedService)-[:OF_TYPE]->(serviceType),
              (providedService)-[:WITH_PROVIDER]->(providerType)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module2UsesService">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (module1)-[:PROVIDES]->(providedService:Java:ProvidedService)-[:OF_TYPE]->(serviceType:Java:Type{fqn:"com.buschmais.jqassistant.plugin.java.it.jpms.module1.api.MyService"}),
              (artifact2:Artifact{name:"java.it.jpms.module2"}),
              (artifact2)-[:CONTAINS]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (module2)-[:USES]->(serviceType)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module2RequiresModule1">
        <cypher><![CDATA[
            MATCH
              (artifact1:Artifact{name:"java.it.jpms.module1"}),
              (artifact1)-[:CONTAINS]->(module1:Java:Module{fqn:"java.it.jpms.module1"}),
              (artifact2:Artifact{name:"java.it.jpms.module2"}),
              (artifact2)-[:CONTAINS]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (module2)-[:REQUIRES]->(module1)
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:OpenModule2">
        <cypher><![CDATA[
            MATCH
              (artifact2:Artifact{name:"java.it.jpms.module2"}),
              (artifact2)-[:CONTAINS]->(module2:Java:Module{fqn:"java.it.jpms.module2", open:true})
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

    <concept id="it:Module2RequiresStaticTransitiveModuleJavaSE">
        <cypher><![CDATA[
            MATCH
              (artifact2:Artifact{name:"java.it.jpms.module2"}),
              (artifact2)-[:CONTAINS]->(module2:Java:Module{fqn:"java.it.jpms.module2"}),
              (module2)-[:REQUIRES{static:true, transitive:true}]->(:Java:Module{fqn:"java.se"})
            RETURN
              *
        ]]></cypher>
        <verify>
            <rowCount min="1" max="1"/>
        </verify>
    </concept>

</jqassistant-rules>

=== jQAssistant/jqassistant/plugin/junit/src/main/resources/META-INF/jqassistant-rules/junit4.xml
<jqassistant-rules xmlns="http://schema.jqassistant.org/rule/v1.10"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://schema.jqassistant.org/rule/v1.10 http://schema.jqassistant.org/rule/jqassistant-rule-v1.10.xsd">

    <group id="junit4:Default">
        <includeConstraint refId="junit4:AssertionMustProvideMessage"/>
        <includeConstraint refId="junit4:NonJUnit4TestMethod"/>
        <includeConstraint refId="junit4:UsageOfJUnit5TestApi"/>
    </group>

    <concept id="junit4:TestMethod">
        <description>Finds all test methods (i.e. annotated with "@org.junit.Test") and labels them with "Test" and
            "Junit4".
        </description>
        <cypher><![CDATA[
            MATCH
              (m:Method)-[:ANNOTATED_BY]-()-[:OF_TYPE]->(a:Type)
            WHERE
              a.fqn="org.junit.Test"
            SET
              m:Test:Junit4
            RETURN
              m AS Test
        ]]></cypher>
    </concept>

    <concept id="junit4:TestClass">
        <requiresConcept refId="junit4:TestMethod"/>
        <description>Labels all classes containing test methods with "Test" and "Junit4".</description>
        <cypher><![CDATA[
            MATCH
              (c:Type:Class)-[:DECLARES]->(m:Method:Junit4:Test)
            SET
              c:Test:Junit4
            RETURN
              c AS TestClass, COLLECT(m) AS TestMethods
        ]]></cypher>
    </concept>

    <concept id="junit4:TestClassOrMethod">
        <requiresConcept refId="junit4:TestMethod"/>
        <requiresConcept refId="junit4:TestClass"/>
        <description>Finds test methods (i.e. annotated with "@org.junit.Test") and labels them and their containing
            classes with "Test" and "Junit4".
        </description>
        <deprecated>This concept has been replaced by "junit4:TestMethod" and "junit4:TestClass".</deprecated>
        <cypher><![CDATA[
            MATCH
              (c:Type:Class)-[:DECLARES]->(m:Method:Junit4:Test)
            RETURN
              c AS TestClass, COLLECT(m) AS TestMethods
        ]]></cypher>
    </concept>

    <concept id="junit4:IgnoreTestClassOrMethod">
        <description>Labels all classes or methods annotated with "@org.junit.Ignore" with "Junit4" and "Ignore".
        </description>
        <cypher><![CDATA[
            MATCH
              (e)-[:ANNOTATED_BY]->()-[:OF_TYPE]->(a:Type)
            WHERE
              a.fqn="org.junit.Ignore"
            SET
              e:Junit4:Ignore
            RETURN
              e AS IgnoredElement
        ]]></cypher>
    </concept>

    <concept id="junit4:BeforeMethod">
        <description>Labels all methods annotated by "@org.junit.Before" with "Junit4" and "Before".</description>
        <cypher><![CDATA[
            MATCH
              (c:Type:Class)-[:DECLARES]->(m:Method),
              (m:Method)-[:ANNOTATED_BY]->()-[:OF_TYPE]->(a:Type)
            WHERE
              a.fqn="org.junit.Before"
            SET
              m:Junit4:Before
            RETURN
              m AS BeforeMethod, c AS TestClass
        ]]></cypher>
    </concept>

    <concept id="junit4:AfterMethod">
        <description>Labels all methods annotated by "@org.junit.After" with "Junit4" and "After".</description>
        <cypher><![CDATA[
            MATCH
              (c:Type:Class)-[:DECLARES]->(m:Method),
              (m:Method)-[:ANNOTATED_BY]->()-[:OF_TYPE]->(a:Type)
            WHERE
              a.fqn="org.junit.After"
            SET
              m:Junit4:After
            RETURN
              m AS AfterMethod, c AS TestClass
        ]]></cypher>
    </concept>

    <concept id="junit4:BeforeClassMethod">
        <description>Labels all methods annotated by "@org.junit.BeforeClass" with "Junit4" and "BeforeClass".
        </description>
        <cypher><![CDATA[
            MATCH
              (c:Type:Class)-[:DECLARES]->(m:Method),
              (m:Method)-[:ANNOTATED_BY]->()-[:OF_TYPE]->(a:Type)
            WHERE
              a.fqn="org.junit.BeforeClass"
            SET
              m:Junit4:BeforeClass
            RETURN
              m AS BeforeClassMethod, c AS TestClass
        ]]></cypher>
    </concept>

    <concept id="junit4:AfterClassMethod">
        <description>Labels all methods annotated by "@org.junit.AfterClass" with "Junit4" and "AfterClass".
        </description>
        <cypher><![CDATA[
            MATCH
              (c:Type:Class)-[:DECLARES]->(m:Method),
              (m:Method)-[:ANNOTATED_BY]->()-[:OF_TYPE]->(a:Type)
            WHERE
              a.fqn="org.junit.AfterClass"
            SET
              m:Junit4:AfterClass
            RETURN
              m AS AfterClassMethod, c AS TestClass
        ]]></cypher>
    </concept>



    <concept id="junit4:AssertMethod">
        <description>Labels all assertion methods declared by org.junit.Assert with "Junit4" and "Assert".</description>
        <cypher><![CDATA[
            MATCH
              (assertType:Type)-[:DECLARES]->(assertMethod)
            WHERE
              assertType.fqn = 'org.junit.Assert'
              and assertMethod.signature =~ 'void assert.*'
            SET
              assertMethod:Junit4:Assert
            RETURN
              assertMethod
            ]]></cypher>
    </concept>

    <concept id="junit4:SuiteClass">
        <description>Labels all classes annotated by "@org.junit.runners.Suite.SuiteClasses" with "Junit4" and "Suite" and creates a relation "CONTAINS_TESTCLASS" to all referenced classes.</description>
        <cypher><![CDATA[
            MATCH
              (suite:Type)-[:ANNOTATED_BY]->(suiteClasses)-[:OF_TYPE]->(suiteClassesType:Type)
            WHERE
              suiteClassesType.fqn = "org.junit.runners.Suite$SuiteClasses"
            SET
              suite:Junit4:Suite
            WITH
              suite, suiteClasses
            MATCH
              (suiteClasses)-[:HAS]->(:Array:Value)-[:CONTAINS]->(Class:Value)-[:IS]->(testClass:Type)
            MERGE
              (suite)-[c:CONTAINS_TESTCLASS]->(testClass)
            RETURN
              suite, collect(testClass)
      ]]></cypher>
    </concept>

    <concept id="junit4:InnerTestClass">
        <requiresConcept refId="junit4:TestClass" />
        <description>Labels inner types of types labeled with "Test" with "Test" and "Inner".</description>
        <cypher><![CDATA[
            MATCH
                (source:Type:Junit4:Test)-[:DECLARES]->(target:Type)
            SET
                target:Junit4:Test:Inner
            RETURN
                target
        ]]></cypher>
    </concept>

    <constraint id="junit4:AssertionMustProvideMessage">
        <requiresConcept refId="junit4:AssertMethod"/>
        <description>All assertions must provide a message.</description>
        <cypher><![CDATA[
            MATCH
              (testType:Type)-[:DECLARES]->(testMethod:Method),
              (testMethod)-[invocation:INVOKES]->(assertMethod:Junit4:Assert:Method)
            WHERE
              NOT assertMethod.signature =~ 'void assert.*\\(java.lang.String,.*\\)'
            RETURN
              invocation AS Invocation,
              testType AS DeclaringType,
              testMethod AS Method
        ]]></cypher>
    </constraint>

    <constraint id="junit4:NonJUnit4TestMethod">
        <requiresConcept refId="junit3:TestMethod"/>
        <requiresConcept refId="junit5:TestMethod"/>
        <requiresConcept refId="junit5:RepeatedTestMethod"/>
        <requiresConcept refId="junit5:ParameterizedTestMethod"/>
        <description>Only the jUnit 4-test annotation must be used to identify test methods in a jUnit 4-based project.</description>
        <cypher><![CDATA[
            MATCH
              (:Artifact)-[:CONTAINS]->(t:Type)-[:DECLARES]->(m:Test:Method)
            WHERE
              m:Junit3 OR m:Junit5
            RETURN
              t AS TestClass,
              m AS TestMethod
        ]]></cypher>
        <report primaryColumn="TestMethod"/>
    </constraint>

    <constraint id="junit4:UsageOfJUnit5TestApi">
        <requiresConcept refId="junit4:TestMethod"/>
        <requiresConcept refId="junit5:TestMethod"/>
        <requiresConcept refId="junit5:RepeatedTestMethod"/>
        <requiresConcept refId="junit5:ParameterizedTestMethod"/>
        <requiresConcept refId="junit5:AssertMethod"/>
        <description>Only the jUnit 4-test api must be used in a jUnit 4-based project.</description>
        <cypher><![CDATA[
            MATCH
              (:Artifact)-[:CONTAINS]->(t:Type)-[:DECLARES]->(m:Test:Method),
              (m)-[:INVOKES*..3]->(:Junit5:Assert:Method)
            RETURN DISTINCT
              t AS TestClass,
              m AS TestMethod
        ]]></cypher>
        <report primaryColumn="TestMethod"/>
    </constraint>

</jqassistant-rules>
